
import { County }    from './county';

export const COUNTIES: County[] = [
    {"County":"Alachua","County_Code":394,"State":"Florida"},
    {"County":"Baker","County_Code":395,"State":"Florida"},
    {"County":"Bay","County_Code":396,"State":"Florida"},
    {"County":"Bradford","County_Code":397,"State":"Florida"},
    {"County":"Brevard","County_Code":398,"State":"Florida"},
    {"County":"Broward","County_Code":399,"State":"Florida"},
    {"County":"Calhoun","County_Code":400,"State":"Florida"},
    {"County":"Charlotte","County_Code":401,"State":"Florida"},
    {"County":"Citrus","County_Code":402,"State":"Florida"},
    {"County":"Clay","County_Code":403,"State":"Florida"},
    {"County":"Collier","County_Code":404,"State":"Florida"},
    {"County":"Columbia","County_Code":405,"State":"Florida"},
    {"County":"DeSoto","County_Code":406,"State":"Florida"},
    {"County":"Dixie","County_Code":407,"State":"Florida"},
    {"County":"Duval","County_Code":408,"State":"Florida"},
    {"County":"Escambia","County_Code":409,"State":"Florida"},
    {"County":"Flagler","County_Code":410,"State":"Florida"},
    {"County":"Franklin","County_Code":411,"State":"Florida"},
    {"County":"Gadsden","County_Code":412,"State":"Florida"},
    {"County":"Gilchrist","County_Code":413,"State":"Florida"},
    {"County":"Glades","County_Code":414,"State":"Florida"},
    {"County":"Gulf","County_Code":415,"State":"Florida"},
    {"County":"Hamilton","County_Code":416,"State":"Florida"},
    {"County":"Hardee","County_Code":417,"State":"Florida"},
    {"County":"Hendry","County_Code":418,"State":"Florida"},
    {"County":"Hernando","County_Code":419,"State":"Florida"},
    {"County":"Highlands","County_Code":420,"State":"Florida"},
    {"County":"Hillsborough","County_Code":421,"State":"Florida"},
    {"County":"Holmes","County_Code":422,"State":"Florida"},
    {"County":"Indian River","County_Code":423,"State":"Florida"},
    {"County":"Jackson","County_Code":424,"State":"Florida"},
    {"County":"Jefferson","County_Code":425,"State":"Florida"},
    {"County":"Lafayette","County_Code":426,"State":"Florida"},
    {"County":"Lake","County_Code":427,"State":"Florida"},
    {"County":"Lee","County_Code":428,"State":"Florida"},
    {"County":"Leon","County_Code":429,"State":"Florida"},
    {"County":"Levy","County_Code":430,"State":"Florida"},
    {"County":"Liberty","County_Code":431,"State":"Florida"},
    {"County":"Madison","County_Code":432,"State":"Florida"},
    {"County":"Manatee","County_Code":433,"State":"Florida"},
    {"County":"Marion","County_Code":434,"State":"Florida"},
    {"County":"Martin","County_Code":435,"State":"Florida"},
    {"County":"Miami-Dade","County_Code":436,"State":"Florida"},
    {"County":"Monroe","County_Code":437,"State":"Florida"},
    {"County":"Nassau","County_Code":438,"State":"Florida"},
    {"County":"Okaloosa","County_Code":439,"State":"Florida"},
    {"County":"Okeechobee","County_Code":440,"State":"Florida"},
    {"County":"Orange","County_Code":441,"State":"Florida"},
    {"County":"Osceola","County_Code":442,"State":"Florida"},
    {"County":"Palm Beach","County_Code":443,"State":"Florida"},
    {"County":"Pasco","County_Code":444,"State":"Florida"},
    {"County":"Pinellas","County_Code":445,"State":"Florida"},
    {"County":"Polk","County_Code":446,"State":"Florida"},
    {"County":"Putnam","County_Code":447,"State":"Florida"},
    {"County":"Saint Johns","County_Code":448,"State":"Florida"},
    {"County":"Saint Lucie","County_Code":449,"State":"Florida"},
    {"County":"Santa Rosa","County_Code":450,"State":"Florida"},
    {"County":"Sarasota","County_Code":451,"State":"Florida"},
    {"County":"Seminole","County_Code":452,"State":"Florida"},
    {"County":"Sumter","County_Code":453,"State":"Florida"},
    {"County":"Suwannee","County_Code":454,"State":"Florida"},
    {"County":"Taylor","County_Code":455,"State":"Florida"},
    {"County":"Union","County_Code":456,"State":"Florida"},
    {"County":"Volusia","County_Code":457,"State":"Florida"},
    {"County":"Wakulla","County_Code":458,"State":"Florida"},
    {"County":"Walton","County_Code":459,"State":"Florida"},
    {"County":"Washington","County_Code":460,"State":"Florida"}
  ]

